apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  labels:
    app: mywebapp
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - name: http
      port: 80
      targetPort: 9886
      protocol: TCP
